apiVersion: v1
kind: Service
metadata:
  name: skycanary
  namespace: skycanary
  labels:
    app: skycanary
spec:
  type: ClusterIP
  selector:
    app: skycanary
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
