apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: skycanary-vs
  namespace: skycanary
spec:
  hosts:
    - "*"
  gateways:
    - skycanary-gateway
  http:
    - route:
        - destination:
            host: skycanary.skycanary.svc.cluster.local
            subset: stable
            port:
              number: 8090
          weight: 90
        - destination:
            host: skycanary.skycanary.svc.cluster.local
            subset: canary
            port:
              number: 8090
          weight: 10
