kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: skycanary
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 8090
        hostPort: 8090
        protocol: TCP
      - containerPort: 32056
        hostPort: 32056
        protocol: TCP
      - containerPort: 30600
        hostPort: 30600
        protocol: TCP
  - role: worker
  - role: worker
